CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CAR_RENTAL_APPLICATION.Models
{
    public class Car
    {
        public int CarId { get; set; }
        public string Brand { get; set; }
        public string Colour { get; set; }
        public string Capacity { get; set; }
        public string NumberOfDoors { get; set; }
        public string FabricationYear { get; set; }

    }
}

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CAR_RENTAL_APPLICATION.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using CAR_RENTAL_APPLICATION.Repositories;
using CAR_RENTAL_APPLICATION.ViewModels;

namespace CAR_RENTAL_APPLICATION.Controllers
{
    public class CarsController : Controller
    {
        private readonly CarsContext _context;
        private readonly IHostingEnvironment hostingEnvironment;

        public CarsController(CarsContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cars.ToListAsync());
        }
        public async Task<IActionResult> Presentation()
        {
            return View(await _context.Cars.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            return View();
        }



        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarsCreateViewModel car)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (car.CarImage != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath + "/images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + car.CarImage.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    car.CarImage.CopyTo(new FileStream(filePath, FileMode.Create));
                  //  string folder = "cars/images";
                  //  folder +=  Guid.NewGuid().ToString() + "_" + car.CarImage.FileName ;
                  //  string serverFolder = Path.Combine(_webHostEnviroment.WebRootPath, folder);

                    //await  car.CarImage.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }
                Car newCar = new Car
                {
                    Brand = car.Brand,
                    Colour = car.Colour,
                    Capacity = car.Capacity,
                    NumberOfDoors = car.NumberOfDoors,
                    FabricationYear = car.FabricationYear,
                    CarImagePath = uniqueFileName

                };
                _context.Add(newCar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarId,Brand,Colour,Capacity,NumberOfDoors,FabricationYear")] Car car)
        {
            if (id != car.CarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.CarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.CarId == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            _context.Cars.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.CarId == id);
        }
    }
}

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CAR_RENTAL_APPLICATION.Models;

namespace CAR_RENTAL_APPLICATION.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly CarsContext _context;

        public PaymentsController(CarsContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            var carsContext = _context.Payments.Include(p => p.PaymentMethod);
            return View(await carsContext.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.PaymentMethod)
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethods, "PaymentMethodId", "PaymentMethodId");
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentId,PaymentMethodId,Amount,TimeStamp")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return Redirect("/Transactions/Create");
            }
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethods, "PaymentMethodId", "PaymentMethodId", payment.PaymentMethodId);
            return View(payment);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethods, "PaymentMethodId", "PaymentMethodId", payment.PaymentMethodId);
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentId,PaymentMethodId,Amount,TimeStamp")] Payment payment)
        {
            if (id != payment.PaymentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethods, "PaymentMethodId", "PaymentMethodId", payment.PaymentMethodId);
            return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.PaymentMethod)
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.Payments.FindAsync(id);
            _context.Payments.Remove(payment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(int id)
        {
            return _context.Payments.Any(e => e.PaymentId == id);
        }
    }
}

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Views/Cars/Create.cshtml
@model CAR_RENTAL_APPLICATION.ViewModels.CarsCreateViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Cars" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfDoors" class="control-label"></label>
                <input asp-for="NumberOfDoors" class="form-control" />
                <span asp-validation-for="NumberOfDoors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FabricationYear" class="control-label"></label>
                <input asp-for="FabricationYear" class="form-control" />
                <span asp-validation-for="FabricationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarImage" class="control-label"></label>
                
                <div class="custom-file">
                    <input asp-for="CarImage" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
         
                <span asp-validation-for="CarImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            })
        })

    </script>
}

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Views/Cars/Delete.cshtml
@model CAR_RENTAL_APPLICATION.Models.Car

@{
    ViewData["Title"] = "Delete";
     Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfDoors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfDoors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FabricationYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FabricationYear)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CarId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Views/Cars/Details.cshtml
@model CAR_RENTAL_APPLICATION.Models.Car

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfDoors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfDoors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FabricationYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FabricationYear)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CarId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Views/Cars/Edit.cshtml
@model CAR_RENTAL_APPLICATION.Models.Car

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CarId" />
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colour" class="control-label"></label>
                <input asp-for="Colour" class="form-control" />
                <span asp-validation-for="Colour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfDoors" class="control-label"></label>
                <input asp-for="NumberOfDoors" class="form-control" />
                <span asp-validation-for="NumberOfDoors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FabricationYear" class="control-label"></label>
                <input asp-for="FabricationYear" class="form-control" />
                <span asp-validation-for="FabricationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Views/Cars/Index.cshtml
@model IEnumerable<CAR_RENTAL_APPLICATION.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<div class="p-4 p-md-5 mb-4 text-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Our offers</h1>
        <p class="lead my-3">
            Choose one of our cars and start driving!
        </p>
    </div>


    <div class="row">
        @foreach (var item in Model)
        {
        <div class="col-sm-12 col-md-6 col-lg-3 pb-4 text-dark">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="images/@Html.DisplayFor(modelItem => item.CarImagePath)" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Brand)</h5>

                    <p class="card-text ">
                       Colour: @Html.DisplayFor(modelItem => item.Colour)
                    </p>
                    <p class="card-text ">
                       Capacity: @Html.DisplayFor(modelItem => item.Capacity)
                    </p>
                    <p class="card-text ">
                       Doors: @Html.DisplayFor(modelItem => item.NumberOfDoors)
                    </p>
                    <p class="card-text ">
                       Year: @Html.DisplayFor(modelItem => item.FabricationYear)
                    </p>
                    <a asp-area="" asp-controller="Payments" asp-action="Create" class="btn btn-dark">Book now!</a>
                </div>
            </div>
        </div>


        }

    </div>




</div>

CAR RENTAL APPLICATION/CAR RENTAL APPLICATION/Views/Cars/Presentation.cshtml
@model IEnumerable<CAR_RENTAL_APPLICATION.Models.Car>


@{
    ViewData["Title"] = "Presentation";
}
<div class=" bg-dark" style="background-image: url(../Assets/under.jpg); ">


    <div class="container-fluid">
        <div class="row">
            



                <main class="container">

                    <div class="p-4 mb-4 text-white  bg-dark">
                        <div class="col-md-6 px-0">
                            <h1 class="display-4 fst-italic">Here’s our showroom location on the map and our cars offering.</h1>
                            <p class="lead my-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id gravida justo, vel mollis massa. Fusce nibh mauris, faucibus porttitor porttitor laoreet, convallis sit amet enim. Nam finibus lorem vitae tempus malesuada.</p>
                            <div class=" map ">
                                <!--<iframe src="https://maps.google.com/maps?q=Craiova&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">></iframe>-->
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d182679.13234702297!2d23.666581347679607!3d44.323076350632654!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4752d70e6d6dcd07%3A0x4650f2eadbde99f9!2sCraiova!5e0!3m2!1sen!2sro!4v1620916469484!5m2!1sen!2sro" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                            </div>
                        </div>
                       

                    </div>


                 
                    <div class="row pt-4 text-white">


                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/shr.jpg);
        background-size: 300px;
">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text ">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

                                </div>
                            </div>
                        </div>


                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/2.jpg);
        background-size: 300px;
">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text ">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>

                                </div>
                            </div>
                        </div>



                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/3.jpg);
        background-size: 300px;
">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text ">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

                                </div>
                            </div>
                        </div>



                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/4.png);
        background-size: 300px;
">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text ">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

                                </div>
                            </div>
                        </div>



                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/5.png);  background-size: 300px;">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text "> Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

                                </div>
                            </div>
                        </div>


                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/car.jpg); background-size: 300px;">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text ">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

                                </div>
                            </div>
                        </div>


                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/car2.jpg); background-size: 300px;">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text ">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

                                </div>
                            </div>
                        </div>


                        <div class="col-sm-12 col-md-6 col-lg-3 pb-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body" style="        background-image: url(../Assets/2.jpg); background-size: 300px;">

                                    <h5 class="card-title">Lorem Ipsum</h5>
                                    <p class="card-text ">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

                                </div>
                            </div>
                        </div>


                    


                    </div>

                </main>

            </div>
        </div>
    </div>



<script>
    function myFunction(id) {
        var x = document.getElementById(id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>